name: first-workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Welcome message
          run: |
            echo "welcome to frist Github actions job"
            ls -lta
            cat README.md
        
        - name: Exceute cowsay command
          run: |
            sudo apt-get install cowsay
            cowsay -f dragon "i am a dragon !!!" > dragon.txt
            cat dragon.txt




