name: generate-ascii

on: push

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Exceute cowsay command
          run: |
            sudo apt-get install cowsay
            cowsay -f dragon "i am a dragon !!!" > dragon.txt

        - name: Upload file
          uses: actions/upload-artifact@v4
          with:
            name: dragon.txt
       
    test-job:
        runs-on: ubuntu-latest
        needs: build-job
        steps:

        - name: Download file
          uses: actions/download-artifact@v4
          with:
            name: dragon.txt

        - name: test dragon
          run: grep -i dragon dragon.txt
        
    deploy-job:
        runs-on: ubuntu-latest
        needs: test-job
        steps:

        - name: Download file
          uses: actions/download-artifact@v4
          with:
            name: dragon.txt
                  
        - name: cat the file
          run: cat dragon.txt

        - name: Deploy
          run: echo "Deploying !!!"