name: test-if-expr-workflow

on: push

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
        
        - name: Start Step
          run: echo Step 1
       
    test-job:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: build-job
        steps:

        - name: Deploy step
          run: echo Deploying github.ref branch
